// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DetailCarte: typeof import('./components/DetailCarte.vue')['default']
    Filtrevalidateur: typeof import('./components/Filtrevalidateur.vue')['default']
    Filtrevisiteur: typeof import('./components/Filtrevisiteur.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    FormCard: typeof import('./components/FormCard.vue')['default']
    FormConnexio: typeof import('./components/FormConnexio.vue')['default']
    HistoriqueUser: typeof import('./components/HistoriqueUser.vue')['default']
    Imgautil: typeof import('./components/Imgautil.vue')['default']
    MobileBar: typeof import('./components/MobileBar.vue')['default']
    MyCard: typeof import('./components/MyCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
  }
}

export { }
