// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountButton: typeof import('./components/layout/navbar/AccountButton.vue')['default']
    AuthenticationButton: typeof import('./components/layout/navbar/AuthenticationButton.vue')['default']
    Footer: typeof import('./components/layout/Footer.vue')['default']
    FormCard: typeof import('./components/createCard/FormCard.vue')['default']
    HistoriqueUser: typeof import('./components/createCard/HistoriqueUser.vue')['default']
    Imgautil: typeof import('./components/createCard/Imgautil.vue')['default']
    InformationCommande: typeof import('./components/InformationCommande.vue')['default']
    InformationUser: typeof import('./components/InformationUser.vue')['default']
    ListCard: typeof import('./components/ListCard.vue')['default']
    ListeProduit: typeof import('./components/ListeProduit.vue')['default']
    ListesProduit: typeof import('./components/ListesProduit.vue')['default']
    LoginForm: typeof import('./components/authentication/login/LoginForm.vue')['default']
    LoginLink: typeof import('./components/authentication/login/LoginLink.vue')['default']
    MyCard: typeof import('./components/MyCard.vue')['default']
    Navbar: typeof import('./components/layout/navbar/Navbar.vue')['default']
    NavbarIcon: typeof import('./components/layout/navbar/NavbarIcon.vue')['default']
    NavbarLinks: typeof import('./components/layout/navbar/NavbarLinks.vue')['default']
    NavbarOptions: typeof import('./components/layout/navbar/NavbarOptions.vue')['default']
    ProductCard: typeof import('./components/products/ProductCard.vue')['default']
    ProductDirectionOrder: typeof import('./components/products/orderBy/ProductDirectionOrder.vue')['default']
    ProductFilter: typeof import('./components/products/ProductFilter.vue')['default']
    ProductList: typeof import('./components/products/ProductList.vue')['default']
    ProductPagination: typeof import('./components/products/filterBy/ProductPagination.vue')['default']
    ProductSearchFilter: typeof import('./components/products/filterBy/ProductSearchFilter.vue')['default']
    ProductStepFilter: typeof import('./components/products/filterBy/ProductStepFilter.vue')['default']
    ProductTypeOrder: typeof import('./components/products/orderBy/ProductTypeOrder.vue')['default']
    RegisterForm: typeof import('./components/authentication/register/RegisterForm.vue')['default']
    RegisterLink: typeof import('./components/authentication/register/RegisterLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShoppingButton: typeof import('./components/layout/navbar/ShoppingButton.vue')['default']
    ShoppingDetails: typeof import('./components/shopping/ShoppingDetails.vue')['default']
    ShoppingPayment: typeof import('./components/shopping/ShoppingPayment.vue')['default']
    ShoppingSummary: typeof import('./components/shopping/ShoppingSummary.vue')['default']
    SwitchDarkMode: typeof import('./components/layout/buttons/SwitchDarkMode.vue')['default']
    SwitchLanguageButton: typeof import('./components/layout/buttons/SwitchLanguageButton.vue')['default']
    UserProductFilter: typeof import('./components/products/filterBy/UserProductFilter.vue')['default']
  }
}

export { }
